"""
Core module for MindPilot.
Contains exceptions, logging, retry, metrics, and validation utilities.
"""
from app.core.exceptions import (
    CacheConnectionException,
    CacheException,
    DatabaseConnectionException,
    DatabaseException,
    DocumentParseException,
    DocumentProcessingException,
    DocumentTooLargeException,
    EmbeddingException,
    EmbeddingTimeoutException,
    ErrorCode,
    LLMException,
    LLMRateLimitException,
    LLMTimeoutException,
    MindPilotException,
    NoRelevantDocsException,
    NotFoundException,
    RetrievalException,
    UnsupportedFormatException,
    ValidationException,
    VectorStoreConnectionException,
    VectorStoreException,
)
from app.core.logger import (
    RequestContext,
    get_logger,
    get_request_id,
    get_session_id,
    get_user_id,
    set_request_id,
    set_session_id,
    set_user_id,
    setup_logging,
)
from app.core.metrics import (
    MetricsMiddleware,
    record_cache_hit,
    record_cache_miss,
    record_embedding,
    record_error,
    record_llm_call,
    record_rag_retrieval,
    record_tokens,
    track_request,
    update_active_sessions,
)
from app.core.observability import (
    TraceContext,
    observability,
    traced,
    track_embedding,
    track_llm,
    track_rag,
    track_retrieval,
)
from app.core.rate_limit import (
    RateLimitConfig,
    RateLimiter,
    RateLimitMiddleware,
    rate_limit,
)
from app.core.retry import (
    CircuitBreaker,
    async_cache_retry,
    async_database_retry,
    async_embedding_retry,
    async_llm_retry,
    async_vector_store_retry,
    cache_breaker,
    cache_retry,
    database_breaker,
    database_retry,
    embedding_breaker,
    embedding_retry,
    llm_breaker,
    llm_retry,
    vector_store_breaker,
    vector_store_retry,
)

__all__ = [
    # Exceptions
    "ErrorCode",
    "MindPilotException",
    "LLMException",
    "LLMTimeoutException",
    "LLMRateLimitException",
    "EmbeddingException",
    "EmbeddingTimeoutException",
    "VectorStoreException",
    "VectorStoreConnectionException",
    "DocumentProcessingException",
    "DocumentParseException",
    "DocumentTooLargeException",
    "UnsupportedFormatException",
    "RetrievalException",
    "NoRelevantDocsException",
    "DatabaseException",
    "DatabaseConnectionException",
    "CacheException",
    "CacheConnectionException",
    "ValidationException",
    "NotFoundException",
    # Logger
    "get_logger",
    "setup_logging",
    "set_request_id",
    "set_user_id",
    "set_session_id",
    "get_request_id",
    "get_user_id",
    "get_session_id",
    "RequestContext",
    # Retry
    "vector_store_retry",
    "embedding_retry",
    "llm_retry",
    "database_retry",
    "cache_retry",
    "async_vector_store_retry",
    "async_embedding_retry",
    "async_llm_retry",
    "async_database_retry",
    "async_cache_retry",
    "CircuitBreaker",
    "vector_store_breaker",
    "embedding_breaker",
    "llm_breaker",
    "database_breaker",
    "cache_breaker",
    # Metrics
    "track_request",
    "record_rag_retrieval",
    "record_embedding",
    "record_llm_call",
    "record_tokens",
    "record_cache_hit",
    "record_cache_miss",
    "record_error",
    "update_active_sessions",
    "MetricsMiddleware",
    # Rate Limit
    "RateLimitMiddleware",
    "RateLimitConfig",
    "RateLimiter",
    "rate_limit",
    # Observability
    "observability",
    "track_llm",
    "track_embedding",
    "track_retrieval",
    "track_rag",
    "traced",
    "TraceContext",
]
